/*

 MAP1.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\Eduardo\Pictures\sprites\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapWidth 40
#define mapHeight 18
#define mapBank 0

unsigned char windowmap[] =
{
  0x18,0x0C,0x0F,0x10,0x00,0x0D,0x24,0x00,0x1D,0x0C,0x1D,0x1A
};

/* End of MAP1.C */
