/*

 DOGTOTAL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Eduardo\Pictures\sprites\dog.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define dogtotalWidth 20
#define dogtotalHeight 18
#define dogtotalBank 0

extern unsigned char dogtotal[];

/* End of DOGTOTAL.H */
